### ISSUE TITLE
Getting Error sh: 1: gs: not found\n

### ISSUE THREAD

**Issue by mahesh-rajawat** [xthiago/pdf-version-converter#19] opened 2018-04-23 09:54 UTC
I am trying to convert version of pdf file from 1.7 to 1.4, i am getting this error: sh: 1: gs: not found\n

**Comment by xthiago** [comment] 2018-07-27 15:37
Hi @maheshWebkul721,

1. You need to have Ghost Script (`gs`) installed in your system. 
2. The library assumes that the `gs` can be executed typing `gs` in your terminal (available in $PATH for *unix systems). If it is not the case, you need to extend `GhostscriptConverterCommand` class and change the `$baseCommand` variable to match the location of your `gs` (E.g. `'/home/user/gs -sDEVICE=pdfwrite [...]'` ). 

https://github.com/xthiago/pdf-version-converter/blob/8c5e309c2351b3e5595898dc27ea18c1a87d4ec1/src/Converter/GhostscriptConverterCommand.php#L25

A good improvement for the library is receive the absolute path to `gs` on `GhostscriptConverterCommand` constructor. Pull-requests are welcome :)

I'm closing this issue since it is not a bug.

**Closed as completed by xthiago** 2018-07-27 15:37 UTC
